[phases.install]
cmds = ['yarn install --mode=skip-build', 'bunx skiller@latest apply && patch-package --patch-dir tooling/patches']

[phases.build]
cmds = ['turbo build']

[start]
cmd = 'yarn next deploy'
