[phases.install]
cmds = ['yarn install --production=false --mode=skip-build', 'bunx skiller@latest apply && bunx patch-package --patch-dir tooling/patches']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'next start'
