
[build]
builder = "RAILPACK"
buildCommand = "yarn install --refresh-lockfile && yarn postinstall && yarn turbo run build --filter=www"

[deploy]
startCommand = "cd apps/www && yarn start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
